### ISSUE TITLE
Different format of output data for different inputs

### ISSUE THREAD

**Issue by faherngeit** [faherngeit/rl_pss#11]
Меняется глубина вложения данных, передаваемых по окончании моделирования, из-за этого сложно унифицировано обрабатывать результаты. 
Пример:
```
out = eng.simWrapper('scenariosNormState', 'IntMaxDeltaWs', 0, 1)
```
Позволяет получить список всех полей следующим образом: 
```
[x for x in data['data'][0]]
```

Но если попросить сделать несколько опытов за раз, то на уровне `data` возникает еще один уровень вложения, о чем заранее можно не знать:
```
out = eng.simWrapper('scenariosNormState', 'IntMaxDeltaWs', 0, 1)
[x for x in data[0]['data'][0]]
```
 Я думаю, было бы хорошо, если бы даже для одного опыта приезжал массив из одного элемента, чтобы можно было обработать его в цикле от 0 до длины массива.

**Comment by MikhailShakirov** [comment]
Странно, вроде как всегда массив должен приезжать. Очень возможно, что матлаб приравнивает массив 1х1 к скаляру и просто забивает на свой синтаксис. Посмотрю

**Comment by MikhailShakirov** [comment]
@faherngeit Как и ожидалось, матлаб кастит массив 1х1 к скаляру и из-за этого становится невозможным отправить json в виде массива 1х1. 
Могу предложить генерировать нулевой элемент-затычку, чтобы "обмануть" матлаб, а при обработке json просто откидывать этот нулевой ничего не значащий элемент массива

**Comment by MikhailShakirov** [comment]
Решил проблему по нормальному - будем всегда получать массив
